### ISSUE TITLE
tree view how to return asynchronously a little confused

### ISSUE THREAD

**Issue by AlaricWeb** [KermanX/reactive-vscode#11]

**Comment by KermanX** [comment]
IMO, the most intuitive way to do this is by using the [`computedAsync`](https://vueuse.org/core/computedAsync/#computedasync) utility from VueUse to convert the async function into a `computed`. Then the `computed` can be passed to `useTreeView`.

Guide about using VueUse in Reactive VSCode: https://kermanx.github.io/reactive-vscode/guide/vueuse.html

**Comment by AlaricWeb** [comment]
Ok,thanks
