### ISSUE TITLE
[Question] How to create multiple useFsWatchers through a reactive array

### ISSUE THREAD

**Issue by Kutius** [KermanX/reactive-vscode#6]
Sorry to bother you..😭 I don't have a clear idea on how to achieve this goal.

```ts
const dirs = shallowRef<string[]>([])

const otherReactiveState = ref(...)

function init() {
  /* ...logic about otherReactiveState... */
  dirs.forEach(d=>{ 
    /*...*/
    watch(d)
  })
}

watchEffect(() => {
  init()
})
```

**Comment by KermanX** [comment]
I updated `useFsWatcher` in the latest version. Now this can be done with the following:

```ts
export  = defineExtension(() => {
  const patterns = computed(() => ["dirs"])
  const watcher = useFsWatcher(patterns)
  watcher.onDidCreate(uri => console.log('create', uri))
}
```

**Comment by Kutius** [comment]
> I updated `useFsWatcher` in the latest version. Now this can be done with the following:
> 
> ```ts
> export = defineExtension(() => {
>   const patterns = computed(() => ["dirs"])
>   const watcher = useFsWatcher(patterns)
>   watcher.onDidCreate(uri => console.log('create', uri))
> }
> ```
> 
> Thank you for coming up with this!

Thanks!

另外我注意到文档里并没有提到 `useFsWatcher` 这个api，可能是遗漏了
