### ISSUE TITLE
The link for Original API in the document is incorrect.

### ISSUE THREAD

**Issue by Ray-D-Song** [KermanX/reactive-vscode#7]
For example, on the page https://kermanx.github.io/reactive-vscode/functions/useStatusBarItem.html, clicking on Original API should redirect to https://code.visualstudio.com/api/references/vscode-api#window.createStatusBarItem. However, it currently redirects to https://code.visualstudio.com/api/references/vscode-api#useQuickPick.

**Comment by KermanX** [comment]
Thanks for reporting🩵

Fixed in 6a91f38cda44faa78513d47bb30ff52c25e5b078
